<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LedgerPay.Application\LedgerPay.Application.csproj" />
    <ProjectReference Include="..\LedgerPay.Domain\LedgerPay.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Persistence\Sql\*.sql" />
  </ItemGroup>

</Project>
